name: Code Review

permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types:
      - closed

jobs:
  review:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container:
      image: chrisai/fair-dao:test
    steps:
      - name: $github
        run:   echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - run: |
          echo ${{join(steps.code_review.outputs.*, '\n')}}
      - run: |
          pip3 install typer web3
      - run: |
          python3 /home/node/evaluate_reward.py ${{github.repository_owner}} ${{github.event.pull_request.base.repo.name}} ${{github.event.number}}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VAULT_PRIVATE_KEY: ${{ secrets.VAULT_PRIVATE_KEY }}
          NETWORK_ID: ${{ secrets.NETWORK_ID }}
      - name: Show success message
        run: echo success!
